"""Per-turn model selection (#35) — converse / remember accept a `provider`
override that routes that one turn through a named registry provider instead of
the bound role, then restores the bound adapter.

Offline-deterministic: monkeypatch the engine's _build_chat_adapter so the
override builds a FakeLLMAdapter (no network). The swap happens under the engine
lock and must be fully restored after the call (next no-override turn uses the
bound adapter again).
"""
import pytest
from fastapi.testclient import TestClient

from starling import _core
from starling.dashboard import DashboardConfig, create_app
from starling.dashboard.engine import DashboardEngine
import starling.dashboard.engine as eng_mod

_STMT_JSON = (
    '[{"holder":"self","holder_perspective":"FIRST_PERSON",'
    '"subject":"Bob","predicate":"responsible_for","object":"auth",'
    '"modality":"BELIEVES","polarity":"POS","nesting_depth":0}]'
)


def _fake(body, ok=True, error=""):
    f = _core.FakeLLMAdapter()
    f.set_default_response(body, ok, error)
    return f


@pytest.fixture(autouse=True)
def _no_env_key(monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)


def test_converse_provider_override_uses_selected_then_restores(tmp_path, monkeypatch):
    cfg = DashboardConfig(db_path=str(tmp_path / "ov.db"), token="")
    cfg.providers["alt"] = {"provider": "openai", "model": "m", "base_url": "", "api_key": "k"}
    eng = DashboardEngine(cfg)
    bound_chat = _fake("DEFAULT-REPLY")
    eng.llm = _fake(_STMT_JSON)        # extraction (remember leg)
    eng._core.chat_llm = bound_chat    # bound chat adapter

    alt = _fake("ALT-REPLY")
    monkeypatch.setattr(eng_mod, "_build_chat_adapter", lambda c: alt)
    client = TestClient(create_app(cfg, engine=eng))

    # provider=alt → reply generated by the alt adapter for this turn
    b = client.post("/api/converse", json={"message": "hi", "provider": "alt"}).json()
    assert b["ok"] is True
    assert b["reply"] == "ALT-REPLY"
    # bound chat adapter restored after the turn (swap is per-turn only)
    assert eng._core.chat_llm is bound_chat
    # next turn with no override falls back to the bound chat adapter
    b2 = client.post("/api/converse", json={"message": "hi"}).json()
    assert b2["reply"] == "DEFAULT-REPLY"


def test_remember_provider_override_uses_selected_then_restores(tmp_path, monkeypatch):
    cfg = DashboardConfig(db_path=str(tmp_path / "rov.db"), token="")
    cfg.providers["alt"] = {"provider": "openai", "model": "m", "base_url": "", "api_key": "k"}
    eng = DashboardEngine(cfg)
    bound = _fake("[]")                # bound extraction: extracts nothing
    eng.llm = bound

    alt = _fake(_STMT_JSON)            # alt provider: extracts a statement
    monkeypatch.setattr(eng_mod, "_build_chat_adapter", lambda c: alt)
    client = TestClient(create_app(cfg, engine=eng))

    b = client.post("/api/remember", json={"text": "Bob owns auth", "provider": "alt"}).json()
    assert len(b["statement_ids"]) >= 1   # the alt adapter did the extraction
    assert eng._core.llm is bound         # bound extraction adapter restored


def test_converse_unknown_provider_is_409(tmp_path):
    cfg = DashboardConfig(db_path=str(tmp_path / "unk.db"), token="")
    eng = DashboardEngine(cfg)
    eng.llm = _fake(_STMT_JSON)
    client = TestClient(create_app(cfg, engine=eng))
    r = client.post("/api/converse", json={"message": "hi", "provider": "ghost"})
    assert r.status_code == 409   # unconfigured provider → LLMNotConfigured → 409


def test_no_provider_uses_bound_role(tmp_path):
    # Regression: omitting `provider` leaves the bound adapter in place (no swap).
    cfg = DashboardConfig(db_path=str(tmp_path / "nb.db"), token="")
    eng = DashboardEngine(cfg)
    bound_chat = _fake("BOUND")
    eng.llm = _fake(_STMT_JSON)
    eng._core.chat_llm = bound_chat
    client = TestClient(create_app(cfg, engine=eng))
    b = client.post("/api/converse", json={"message": "hi"}).json()
    assert b["reply"] == "BOUND"
    assert eng._core.chat_llm is bound_chat
